### PR TITLE
Added Hyperlink and License.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
- Added Hyperlink in "Minimal News" which now redirect to the website
Screenshot 2021-10-03 144938
- Added License Section
License

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
@devansh016 Plz Check

**Review by devansh016 — APPROVED** [review]
Good Work

**Comment by devansh016** [comment]
A big thanks for the contribution, for providing new enhancements to this project.

**Comment by Pradumnasaraf** [comment]
> A big thanks for the contribution, for providing new enhancements to this project.
Thank you so much :)

**Pull request merged**
