### PR TITLE
Footer ui improved

### PR DESCRIPTION
**Pull request by preeti-14-7**
I have changed the footer content and also add hover effect on social icons. Changed the footer background colour with theme.

### CODE REVIEW

**Comment by devansh016** [comment]
Can you please attach a screenshot.

**Comment by devansh016** [comment]
Can you resolve the conflicts.

**Comment by preeti-14-7** [comment]
> Can you please attach a screenshot.

https://user-images.githubusercontent.com/73853439/135834906-eb688d1a-afbe-4377-a32c-f7aab95525e0.mp4

**Comment by preeti-14-7** [comment]
I don;t know why news section part is not coming when i hosted it in my server

**Comment by devansh016** [comment]
> > Can you please attach a screenshot.
> 
>  git.mp4

I approve the changes but there are conflicts  in this branch. You can fork the repo again and copy the changes and send a pr. The project directory was restructured.

**Comment by devansh016** [comment]
> I don;t know why news section part is not coming when i hosted it in my server

I would advice you to refork the repo this issue is solved.

**Comment by preeti-14-7** [comment]
> > I don;t know why news section part is not coming when i hosted it in my server
> 
> I would advice you to refork the repo this issue is solved.

Resolved the issue please check it again

**Review by devansh016 — APPROVED** [review]
Thanks for the contribution.

**Comment by preeti-14-7** [comment]
will it not be merged ?

**Comment by devansh016** [comment]
footer
Footer is not going well with the looks of the website.

**Comment by devansh016** [comment]
Repo is accepted for hacktoberfest.

**Comment by preeti-14-7** [comment]
> Pull request is accepted for hacktoberfest.

NO it will not be counted because .. it is not merged ...

Well No issue!! Can you provide some design like really what kind you want so that i can do and make the pr again?

**Comment by devansh016** [comment]
PR with the hacktoberfest-accepted label are counted. You can change the color and remove the shadow and also match the color with dark theme. color should be similar to the main color of the website.

**Pull request closed without merging**
