### PR TITLE
added validation for article to counter Null or undefine content

### PR DESCRIPTION
**Pull request by itsdharmxd**
i have added a validation layer to counter this issue please review

### CODE REVIEW

**Comment by devansh016** [comment]
Can you please include a screenshot? What's happens when a null value is detected?

**Comment by itsdharmxd** [comment]
Hey **@devansh016**  i mock the article to have a null value 

image

then here i receive null(which is pass as a string in .txt file)
displays null
image

Now i uncomment  validateArticle function and it will convert (if it is empty ,null or undefine)null ->""    if 

image

now all Null value replace  by "" <- empty string

image

**Comment by itsdharmxd** [comment]
@devansh016  please  take a review  on this

**Review by devansh016 — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
