### PR TITLE
fix: header style & footer dark mode style

### PR DESCRIPTION
**Pull request by adibemohamed**
hi there 
here's some improvements of navbar & footer style

### CODE REVIEW

**Comment by adibemohamed** [comment]
fixed

Screenshot from 2021-10-05 16-01-11

**Comment by devansh016** [comment]
> fixed
> 
> Screenshot from 2021-10-05 16-01-11

commit the changes will approve

**Comment by adibemohamed** [comment]
done

**Review by devansh016 — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
