### PR TITLE
Added fade up animate on scroll effect

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**

### CODE REVIEW

**Comment by Muhammed-Rahif** [comment]
## Animation can increase user experience... That's why I add this animation.. 

@devansh016 Preview :-
aos

Sorry for the fast preview... Hope that you can understand what is changed!

**Comment by devansh016** [comment]
@yashchaudhari008 should we include this? Will this be distracting for user or will align with our minimal news goal?

**Comment by yashchaudhari008** [comment]
> @yashchaudhari008 should we include this? Will this be distracting for user or will align with our minimal news goal?

Animation breaks at end of page.
Thanks for considering me @devansh016 , I personally think animations are great.
But in this case, I think animation should be more subtle.
I also notice that if we fast scroll, cards are loads in bulk (means 4-5 cards follow same animation) making app look kinda laggy.

**Review by devansh016 — APPROVED** [review]
good work

**Comment by devansh016** [comment]
Thanks for the contribution. I have approved this PR for hacktoberfest but will not be merging this Pull Request. @Muhammed-Rahif

**Comment by Muhammed-Rahif** [comment]
> > @yashchaudhari008 should we include this? Will this be distracting for user or will align with our minimal news goal?
> > 
> > Animation breaks at end of page.
> > Thanks for considering me @devansh016 , I personally think animations are great.
> > But in this case, I think animation should be more subtle.
> > I also notice that if we fast scroll, cards are loads in bulk (means 4-5 cards follow same animation) making app look kinda laggy.

Yeah... I noticed that... 👍
I will be back with another feature or something else... If there is one to work on, please mention...

And thank you very much to accepting for hacktoberfest...❤️😊

**Pull request closed without merging**
