### PR TITLE
Fixed Contributor Page UI and scroll-to-top button colour.

### PR DESCRIPTION
**Pull request by yashchaudhari008**

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
Should I also fix footer UI, or someone is working on it?

**Comment by devansh016** [comment]
> Should I also fix footer UI, or someone is working on it?

Footer work has already been assigned and I already received a PR for same.

**Comment by yashchaudhari008** [comment]
> > Should I also fix footer UI, or someone is working on it?
> 
> Footer work has already been assigned and I already received a PR for same.

Okay, I will not added new changes then. What about this PR?

**Review by devansh016 — APPROVED** [review]

**Comment by devansh016** [comment]
Thanks for the contribution.

**Pull request merged**
