### PR TITLE
fix(style): fixed UI inconsistencies in dark mode & responsiveness

### PR DESCRIPTION
**Pull request by boidushya**
Added proper padding and indentation for consistency in mobile devices
Added consistent drop shadow for theme change button for both light and dark modes
Fixed styling inconsistencies for dark mode

### CODE REVIEW

**Comment by boidushya** [comment]
Previews: 
image
image
image

**Review by devansh016 — APPROVED** [review]
Good Work

**Comment by devansh016** [comment]
A big thanks for the contribution, for providing new enhancements to this project.

**Comment by boidushya** [comment]
no worries :)

**Pull request merged**
