### PR TITLE
feat: fetch news by country

### PR DESCRIPTION
**Pull request by adibemohamed**
Hi there :wave:
I've added some changes, mainly:
1. Fetch news by country
2. Fix home page header (add images)

Screenshot from 2021-10-04 01-38-33

### CODE REVIEW

**Comment by devansh016** [comment]
@adibemohamed Thanks for such a good contribution love the UI changes. 
Currently we  are using the free plan of the newsapi and limited to 100 calls per day that's why I'm making a call every hour to update news and cache them on our server.  So we have 24 calls per country per day and can't implement multiple countries right now. If we implement multiple countries we will be only updating news twice a day only.

**Comment by devansh016** [comment]
You can send a new PR for the UI changes and I will approve it. We can further discuss about the scope of multiple countries you can create a new issue for this.
Thanks for the contribution. I really appreciate your efforts.

**Comment by adibemohamed** [comment]
Remove country select feature & Add Header style.

**Comment by devansh016** [comment]
@adibemohamed This PR is having lots of conflicts due to prettier. I'm approving the changes but will not be able to merge the PR can you send a new PR.

**Review by devansh016 — APPROVED** [review]
Thanks for the contribution.

**Comment by devansh016** [comment]
I think we should consider using mvc architecture and restructure our code.

**Comment by devansh016** [comment]
@adibemohamed Can you please send a PR with the UI changes you did. I really like them.

**Pull request closed without merging**
