### PR TITLE
closes #34   add footer

### LINKED ISSUE #34: Add a responsive footer

### PR DESCRIPTION
**Pull request by Sejal-16**
closes #34

### CODE REVIEW

**Comment by devansh016** [comment]
@Sejal-16 Can you please attach a screenshot.

**Comment by devansh016** [comment]
https://user-images.githubusercontent.com/58871818/135760359-9a059f36-f874-44ad-8654-2695f21cbf0f.mp4

The footer should not be stickey like this it.

**Review by devansh016 — APPROVED** [review]
A big thanks for the contribution, for providing new enhancements to this project. I really appreciate the efforts you are putting in this project.

**Comment by Sejal-16** [comment]
But there are conflicts , will you be merging it ?

**Comment by devansh016** [comment]
Conflicts resolved.

**Pull request merged**
