### PR TITLE
Update footer

### LINKED ISSUE #72: Update footer content with links
I think we need a more content footer with showing links to explore our website. Also we need links for supporting us and following! 

And the benfit is if the user is scrolled down to the bottom of our website, and user need to go another router or link, you know it is easy if there are links in footer.

So I created a updated footer design in my local project! Here is how it looks like :-
desktop
mob

Hope you got what I mean!

### PR DESCRIPTION
**Pull request by Muhammed-Rahif**
# Resolves #72 
### Preview :- 
desktop
mob

@devansh016

### CODE REVIEW

**Comment by devansh016** [comment]
@Muhammed-Rahif Can you increase the column width for the below, so more text can be seen in a line.
If the above changes look better you can commit them, if not no problem will approve the pr.
Capturee

**Comment by Muhammed-Rahif** [comment]
### Without width for subtitle :-
Screen Shot 2021-10-06 at 23 52 27

### With width for subtitle :-
Screen Shot 2021-10-06 at 23 52 34


@devansh016 I think the second one is better!

**Comment by devansh016** [comment]
@Muhammed-Rahif Yes second is better.

**Comment by Muhammed-Rahif** [comment]
@devansh016 Sorry A mistake!

**Pull request merged**
