### PR TITLE
Add scroll to top button

### PR DESCRIPTION
**Pull request by vaishnav-sh**
changed the scroll to top button to be responsive and fit the layout

### CODE REVIEW

**Comment by devansh016** [comment]
@vaishnav-sh Can you please upload the screenshot.

**Comment by vaishnav-sh** [comment]
image

**Comment by vaishnav-sh** [comment]
image
image

**Review by devansh016 — APPROVED** [review]
Good Work

**Comment by vaishnav-sh** [comment]
Thank you! Is this hacktoberfest-accepted?

**Comment by devansh016** [comment]
yes

**Pull request merged**
