### PR TITLE
Handle null values from the API

### PR DESCRIPTION
**Pull request by boehs**

### CODE REVIEW

**Review by devansh016 — APPROVED** [review]
Good work

**Review by devansh016 — COMMENTED** [review]
these chnages are breaking the site

**Comment by boehs** [comment]
What are they doing? I will test and fix what ever is happening

**Comment by devansh016** [comment]
news sources or description are null by default this is breaking the site.

**Comment by boehs** [comment]
Well, that's the point. It's a bad ux if a user sees `null` in their feed

**Comment by devansh016** [comment]
yes we can remove null with blankspace

**Pull request merged**
